# Generated by Django 2.0.7 on 2019-01-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webd', '0002_auto_20190122_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
