# Generated by Django 2.0.7 on 2019-01-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webd', '0003_auto_20190124_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='FormM',
        ),
    ]
